# -*- coding: utf-8 -*-
"""JSON Refiner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcrGuvW3ynG963WpFSKN01goqnmbxqq9
"""

!pip install gradio

!pip install gradio

import gradio as gr
import json
import ast
from collections import OrderedDict
from datetime import datetime

history = []

def parse_value(value):

    value = value.strip()

    if value.lower() == "true":
        return True

    if value.lower() == "false":
        return False

    if value.lower() == "null":
        return None

    try:
        if "." in value:
            return float(value)
        return int(value)
    except:
        pass

    try:
        return ast.literal_eval(value)
    except:
        pass

    return value

def convert_case(key, style):

    if style == "snake_case":
        return key.lower().replace(" ", "_")

    if style == "camelCase":
        parts = key.split("_")
        return parts[0] + ''.join(word.capitalize() for word in parts[1:])

    if style == "PascalCase":
        return ''.join(word.capitalize() for word in key.split("_"))

    if style == "kebab-case":
        return key.lower().replace("_","-")

    return key

def flatten_json(data, parent_key="", sep="_"):

    items = []

    for k,v in data.items():

        new_key = parent_key + sep + k if parent_key else k

        if isinstance(v,dict):
            items.extend(flatten_json(v,new_key,sep).items())
        else:
            items.append((new_key,v))

    return dict(items)

def unflatten_json(data):

    result = {}

    for key,value in data.items():

        parts = key.split("_")

        d = result

        for part in parts[:-1]:

            if part not in d:
                d[part] = {}

            d = d[part]

        d[parts[-1]] = value

    return result

def merge_json(json1,json2):

    try:

        obj1 = json.loads(json1)
        obj2 = json.loads(json2)

        obj1.update(obj2)

        return json.dumps(obj1,indent=4)

    except Exception as e:
        return str(e)

def validate_json(text):

    try:

        json.loads(text)

        return "Valid JSON ✅"

    except:

        return "Invalid JSON ❌"

def refine_json(text,case_style,flatten_option):

    result = OrderedDict()

    lines = text.strip().split("\n")

    for line in lines:

        if ":" in line:

            key,value = line.split(":",1)

            key = convert_case(key.strip(),case_style)

            value = parse_value(value)

            result[key] = value

    if flatten_option:

        result = flatten_json(result)

    output = json.dumps(result,indent=4)

    history.append({
        "time":str(datetime.now()),
        "output":output
    })

    return output

def show_history():

    text=""

    for h in history:

        text += f"\nTime : {h['time']}\n"
        text += f"{h['output']}\n"
        text += "------------------\n"

    return text

guide_text = """
Input Format Example

name: John Doe
age: 28
is_active: true
balance: 1500.50

Features

Core Refining
Validation
Case Conversion
Flatten JSON
Merge JSON
History Tracking
"""

with gr.Blocks() as app:

    gr.Markdown("# JSON Refiner Advanced Edition")

    with gr.Tab("Core Refining"):

        input_text = gr.Textbox(label="Key Value Input",lines=10)

        case_style = gr.Radio(
            ["snake_case","camelCase","PascalCase","kebab-case"],
            value="snake_case",
            label="Case Style"
        )

        flatten_option = gr.Checkbox(label="Flatten JSON")

        run_btn = gr.Button("Refine")

        output_json = gr.Code(language="json")

        run_btn.click(
            refine_json,
            inputs=[input_text,case_style,flatten_option],
            outputs=output_json
        )

    with gr.Tab("Validation"):

        json_input = gr.Textbox(label="Enter JSON")

        validate_btn = gr.Button("Validate")

        validation_output = gr.Textbox()

        validate_btn.click(
            validate_json,
            inputs=json_input,
            outputs=validation_output
        )

    with gr.Tab("Merge JSON"):

        json1 = gr.Textbox(label="JSON 1")

        json2 = gr.Textbox(label="JSON 2")

        merge_btn = gr.Button("Merge")

        merge_output = gr.Code(language="json")

        merge_btn.click(
            merge_json,
            inputs=[json1,json2],
            outputs=merge_output
        )

    with gr.Tab("Flatten / Unflatten"):

        flat_input = gr.Textbox(label="JSON Input")

        flatten_btn = gr.Button("Flatten")

        unflatten_btn = gr.Button("Unflatten")

        flat_output = gr.Code(language="json")

        flatten_btn.click(
            lambda x: json.dumps(flatten_json(json.loads(x)),indent=4),
            inputs=flat_input,
            outputs=flat_output
        )

        unflatten_btn.click(
            lambda x: json.dumps(unflatten_json(json.loads(x)),indent=4),
            inputs=flat_input,
            outputs=flat_output
        )

    with gr.Tab("History"):

        history_btn = gr.Button("Show History")

        history_box = gr.Textbox(lines=15)

        history_btn.click(
            show_history,
            outputs=history_box
        )

    with gr.Tab("Guide"):

        gr.Markdown(guide_text)

app.launch()